name: send reminder 3

on:
  schedule:
   - cron: '0 1 28 1,3,5,7,8,10,12 *' # At 01:00 3 days before end of the month
   - cron: '0 1 27 4,6,9,11 *'
   - cron: '0 1 25 2 *'
  workflow_dispatch:

jobs:
  send_reminder_3:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v5

      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-venv python3-pip wkhtmltopdf xfonts-75dpi xfonts-base

      - name: setup venv
        run: ./venvsetup.sh

      - name: run gazbot
        env:
          GAZBOT_SERVER: ${{ secrets.GAZBOT_SERVER }}
          GAZBOT_USERNAME: ${{ vars.GAZBOT_USERNAME }}
          GAZBOT_PASSWORD: ${{ secrets.GAZBOT_PASSWORD }}
          GAZBOT_ADDRESSES: ${{ secrets.GAZBOT_ADDRESSES }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_SENDER: ${{ vars.SMTP_SENDER }}
        run: |
          source .venv/bin/activate
          python gazbot.py --reminder 3
