name: send reminder 2

on:
  schedule:
   - cron: '0 1 29 1,3,5,7,8,10,12 *' # At 01:00 2 days before end of the month
   - cron: '0 1 28 4,6,9,11 *'
   - cron: '0 1 26 2 *'
  workflow_dispatch:

jobs:
  send_reminder_2:
    runs-on: self-hosted
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup venv
        run: ./venvsetup.sh

      - name: run gazbot
        run: |
          source ~/gaz_env.sh
          source .venv/bin/activate
          python gazbot.py --server $GAZBOT_SERVER --username $GAZBOT_USERNAME --password $GAZBOT_PASSWORD --reminder 2
