name: send reminder 0

on:
  schedule:
   - cron: '0 1 31 1,3,5,7,8,10,12 *' # At 01:00 0 day before end of the month
   - cron: '0 1 30 4,6,9,11 *'
   - cron: '0 1 28 2 *'
  workflow_dispatch:

jobs:
  send_reminder_0:
    runs-on: self-hosted
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup venv
        run: ./venvsetup.sh

      - name: run gazbot
        run: |
          source ~/gaz_env.sh
          source .venv/bin/activate
          python gazbot.py --server $GAZBOT_SERVER --username $GAZBOT_USERNAME --password $GAZBOT_PASSWORD --address ~/address.txt --reminder 0
