name: send gazette

on:
  schedule:
   - cron: '0 0 2 * *' # At 01:00 second day of month
  workflow_dispatch:

jobs:
  send_gazette:
    runs-on: ubuntu-latest  # <-- Runner GitHub au lieu de self-hosted
    steps:
      - name: checkout repo content
        uses: actions/checkout@v5

      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-venv python3-pip wkhtmltopdf xfonts-75dpi xfonts-base

      - name: setup venv
        run: ./venvsetup.sh

      - name: run gazbot
        env:
          GAZBOT_SERVER: ${{ secrets.GAZBOT_SERVER }}
          GAZBOT_USERNAME: ${{ vars.GAZBOT_USERNAME }}
          GAZBOT_PASSWORD: ${{ secrets.GAZBOT_PASSWORD }}
          GAZBOT_ADDRESSES: ${{ vars.GAZBOT_ADDRESSES }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ vars.SMTP_PORT }}
          SMTP_USERNAME: ${{ vars.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          SMTP_SENDER: ${{ vars.SMTP_SENDER }}
        run: |
          export XDG_RUNTIME_DIR="/tmp/runtime-$(whoami)"
          source .venv/bin/activate
          python gazbot.py --gazette