name: send gazette

on:
  schedule:
   - cron: '0 0 2 * *' # At 01:00 second day of month
  workflow_dispatch:

jobs:
  send_gazette:
    runs-on: self-hosted
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content
        
      - name: setup venv
        run: ./venvsetup.sh

      - name: create address file
        env:
          GAZBOT_ADDRESSES: ${{ vars.GAZBOT_ADDRESSES }}
        run: echo "$GAZBOT_ADDRESSES" | tr '\n' > address.txt

      - name: run gazbot
        env:
          GAZBOT_SERVER: ${{ vars.GAZBOT_SERVER }}
          GAZBOT_USERNAME: ${{ vars.GAZBOT_USERNAME }}
          GAZBOT_PASSWORD: ${{ secrets.GAZBOT_PASSWORD }}
          SMTP_SERVER: ${{ vars.SMTP_SERVER }}
          SMTP_USERNAME: ${{ vars.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          SMTP_SENDER: ${{ vars.SMTP_SENDER }}
        run: |
          cat address.txt
          #source .venv/bin/activate
          #python gazbot.py --server $GAZBOT_SERVER --username $GAZBOT_USERNAME --password $GAZBOT_PASSWORD --smtp_server $SMTP_SERVER --smtp_username $SMTP_USERNAME --smtp_password $SMTP_PASSWORD --smtp_sender $SMTP_SENDER --address address.txt --gazette 0
